### PR TITLE
Added a Red Alert 2 .map importer and terrain lighting

### PR DESCRIPTION
**Pull request by Mailaender**
Thanks to @MustaphaTR and @GraionDilach.

Source of the maps:

```
./utility.sh --extract valley.map
./utility.sh --extract dustbowl.map
./utility.sh --extract break.map
./utility.sh --extract powdrkeg.map
./utility.sh --extract tsunami.map
./utility.sh --extract valley.map
```

from inside the .mix of https://xwis.net/Dl/Red-Alert-2-Multiplayer.exe

### CODE REVIEW

**Comment by abcdefg30** [comment]
This needs a rebase now.

**Comment by MustaphaTR** [comment]
Maps in the original game usually have overrides for lamp values, have you checked the maps here for them? Default values are too bright usually.

**Comment by Mailaender** [comment]
Identified more maps using http://www.cncforen.de/archive/index.php?t-6533.html reimported almost all of them and added missing overlays.

**Comment by penev92** [comment]
Realizing that if my current effort upstream to improve TS map importing (https://github.com/OpenRA/OpenRA/pull/20784) bears any fruit these maps may need to be reimported and the map importer reworked, I'm willing to merge this in the mean time in order to hopefully get things moving and because there are actual improvements to at least some of the maps here. I'll then do the rebasing of #806 and addressing style rule violations myself.

**Review by penev92 — APPROVED** [review]

**Pull request merged**
