### PR TITLE
Remove AnnounceOnKill from Kirov Airship

### PR DESCRIPTION
**Pull request by MustaphaTR**
Moved Phrohdoh/OpenRA#81 to here.

#1 had to be splited anyway. This can be deleted from there.

### CODE REVIEW

**Comment by abcdefg30** [comment]
This looks good, but please add `DeathSounds:` to `^Aircraft` in `defaults.yaml`.

**Comment by MustaphaTR** [comment]
But not all aircrafts have a death sound? But most of them i think so i'll.

**Comment by abcdefg30** [comment]
I think all aircraft units (`kirovs`, `harriers` (`black eagels`) and `night hawks`) had death sounds.

**Comment by MustaphaTR** [comment]
Paradrop Plane, Osprey and Hornets don't have a death sound, but hit(crash) sounds.

**Comment by abcdefg30** [comment]
Those would get a `-DeathSounds:` then.

**Comment by abcdefg30** [comment]
We can also add `DeathSounds:` only to the `kirov` (and later to the other units which need that, when we add them). I'm actually ok with both.

**Comment by MustaphaTR** [comment]
Updated. Added `DeathSounds:` to `^Aircraft`.

**Comment by abcdefg30** [comment]
:+1:

**Pull request merged**
