### PR TITLE
Added high bridges and A Path Beyond II

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/ra2/issues/188.

### CODE REVIEW

**Comment by sorcerer86pt** [comment]
Issue with High Bridges. Any unit with C4 (Tanya, seal, chrono commando, yuri commando) should destroy bridge if the bridge repair gets targeted. But it doesn't. See video link.



Base Profile Screenshot 2020 03 22 - 16 58 36 90
Base Profile Screenshot 2020 03 22 - 16 59 09 68
Base Profile Screenshot 2020 03 22 - 16 59 12 70
Base Profile Screenshot 2020 03 22 - 16 59 16 07
Base Profile Screenshot 2020 03 22 - 16 59 36 26
Base Profile Screenshot 2020 03 22 - 17 03 30 85

[bridges c4](https://drive.google.com/file/d/1arGWhEWpjplkN01EATM1FhmCYQFXMEBW/view?usp=sharing)

**Comment by Mailaender** [comment]
That isn't implemented yet. https://github.com/OpenRA/OpenRA/issues/8917 is still open.

**Comment by sorcerer86pt** [comment]
ah okay. Them i think you can merge this one. The bridge works (as units can travel through them, and underneath them). And the maps loads correctly.

**Comment by Mailaender** [comment]
I can only remove the bridge huts, but that only hides the problem.

**Pull request merged**
