### PR TITLE
Fixed soviet engineer speaking with allied voice set

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/Phrohdoh/OpenRA/issues/82.

### CODE REVIEW

**Comment by abcdefg30** [comment]
Sorry, we can't take this at the moment: https://github.com/OpenRA/ra2/pull/1#discussion_r48202377

TL;DR: There is no `ienssed`, `iensatc` and `iensdid`, IIRC.

**Comment by Mailaender** [comment]
That shouldn't be a blocker. If the engine can't find the file, it will only log that. Nothing serious happens.

**Comment by abcdefg30** [comment]
But that would mean reverting this after we got an upstream fix like https://github.com/OpenRA/ra2/pull/1#discussion_r48284138:
```
Voiced:
    VoiceSet: AlliedEngineer
    FactionVoiceSets:
        allies: AlliedEngineer
        soviets: SovietEngineer
```
Or like what https://github.com/OpenRA/OpenRA/pull/10422 proposed.

**Comment by Mailaender** [comment]
You probably mean https://github.com/OpenRA/OpenRA/pull/10050 which was already rejected.

**Comment by GraionDilach** [comment]
>If the engine can't find the file, it will only log that. Nothing serious happens.

A muted response is IMO serious. But I guess I'm alone with this.

**Comment by abcdefg30** [comment]
> A muted response is IMO serious. But I guess I'm alone with this.

I think it's a bug that needs fixing too, this at the moment just looks like trading bad yaml with bugs (although it was in principle a good idea to do this).

> You probably mean OpenRA/OpenRA#10050 which was already rejected.

I wouldn't say rejected, the author just closed his pr again (even so fast that I didn't recognized what's actually going on there).

**Comment by GraionDilach** [comment]
This was the reason behind that PR's closure. http://logs.openra.net/?year=2015&month=11&day=21#11:36:32

**Comment by Mailaender** [comment]
Superseded by https://github.com/OpenRA/ra2/pull/106.

**Pull request closed without merging**
