### PR TITLE
Split content metadata into their own files

### PR DESCRIPTION
**Pull request by drifthat**
to match https://github.com/OpenRA/OpenRA/pull/11771.

### CODE REVIEW

**Comment by drifthat** [comment]
CI build is passed now

**Comment by drifthat** [comment]
merged w/ latest master codebase

**Comment by GraionDilach** [comment]
This needs a rebase.

**Comment by Mailaender** [comment]
It looks like the GitHub desktop clients makes things worse by merging in the latest master instead of just rebasing, but I could resolve this with the web interface by squashing things together also eliminating the revert commit which then also let's us avoid a commit that breaks things.

**Comment by GraionDilach** [comment]
I can't tell any desktop GUI client which rebases on default settings, so that doesn't apply to Github's alone.

**Pull request merged**
