### PR TITLE
New RA2 UI (soviets faction updated)

### PR DESCRIPTION
**Pull request by x-a-n-a-x**
New RA2 UI (soviets faction updated)

### CODE REVIEW

**Comment by Mailaender** [comment]
Can we keep power down for now? It is useful for testing and debugging while the mod is in heavy development.

**Comment by abcdefg30** [comment]
Doesn't this only remove the button, but not the feature itself?
If we want to keep it for debug reasons then we can still access it via the hotkeys.

**Comment by x-a-n-a-x** [comment]
@abcdefg30 : indeed, I only modified the graphics.

**Comment by Mailaender** [comment]
> If we want to keep it for debug reasons then we can still access it via the hotkeys.

The hotkey is tied to the UI widget.

**Pull request closed without merging**
