### PR TITLE
RA2 UI without powerdown nor diplomacy buttons

### PR DESCRIPTION
**Pull request by x-a-n-a-x**
RA2 without powerdown nor diplomacy buttons

### CODE REVIEW

**Comment by MustaphaTR** [comment]
I unerstand power, but why no diplomacy button?

Also can you fix #21 when you are in it?

**Comment by x-a-n-a-x** [comment]
I have been told that the Diplomacy button will be removed soon or later. So, there is no point to keep it  in this WIP mod.

**Comment by x-a-n-a-x** [comment]
@OpenRA/engine-hackers : I failed to squash my 3 commits and it ended with this mess. Can someone help me?

**Comment by Iamgoofball** [comment]
Why was power down removed exactly? Depowering un-needed defenses so that I can keep other stuff powered is handy.

**Comment by GraionDilach** [comment]
@Phrohdoh wants the project to be "purist".

**Comment by x-a-n-a-x** [comment]
Some OpenRA players want a RA2 mod with modern RTS features. Others would like a mod close to vanilla. There is no real consensus yet on that topic (if that button should be kept or be removed). That's why I have created two branches, to let developers (and contributors) decide what the RA2 mod will look like.

**Comment by Iamgoofball** [comment]
I'm pretty sure RA2 has Power Down, and quite frankly I feel like this problem is better solved by just having the ability to disable it when setting up a match, so that the people who dont want it are happy and then people like me who want it are happy.

**Comment by Iamgoofball** [comment]
PS. Deliberately not including quality of life changes in the name of "purist" is really bad

**Comment by pchote** [comment]
The original game didn't have it, and adding it fundamentally changes the game balance surrounding power (which is a resource that needs to be managed).  Calling it a quality of life feature is misleading.

**Comment by GraionDilach** [comment]
Many YR modders wished for the feature and gladly tributed the repair button (using autorepair) instead back in the NPatch days.

**Comment by Mailaender** [comment]
Seeing https://github.com/OpenRA/ra2/pull/77/ the game even has BuildingOnline and BuildingOffline notifications.

**Comment by MustaphaTR** [comment]
Red Alert 2 has really lots of unused eva voices. Like War/Chrono Miner Offline, Building Online/Offline. Tertiary Objective Achives and more.

**Comment by Mailaender** [comment]
Superseded by https://github.com/OpenRA/ra2/pull/109 I assume.

**Pull request closed without merging**
