### PR TITLE
Fixed allied grunt not able to take cover

### PR DESCRIPTION
**Pull request by Mailaender**
Depends on https://github.com/OpenRA/OpenRA/pull/17522.

### CODE REVIEW

**Comment by sorcerer86pt** [comment]
needs rebase

**Comment by sorcerer86pt** [comment]
The https://github.com/OpenRA/OpenRA/pull/17522 has been merged, so this one can be rebased and tested

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/commit/037ce9ebf3ad28a771cb16e08559598d230da19f is part of release-20200503 so this should indeed work. Rebased.

**Comment by abcdefg30** [comment]
Am I missing something here? We're not based on `release-20200503` yet.

**Comment by Phrohdoh** [comment]
See #738 for updating the engine to `release-20200503`.

**Comment by Mailaender** [comment]
Rebased.

**Review by abcdefg30 — APPROVED** [review]

**Pull request merged**
