### PR TITLE
Added GI sandbag deployment

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/ra2/issues/189.

It still has some limitations. All of them are engine related:

- [ ] <s>`Crushable` needs to become conditionable.</s> OpenRA/OpenRA#14507
- [ ] `TakeCover` needs to become conditionable.
- [x] `WithInfantryBody` won't aim in the right direction. OpenRA/OpenRA#12738

I also experimented with https://github.com/OpenRA/OpenRA/pull/13736, https://github.com/OpenRA/OpenRA/pull/13143 and https://github.com/OpenRA/OpenRA/pull/13745, but couldn't get them to work. This will need several followups.

### CODE REVIEW

**Comment by MustaphaTR** [comment]
I'm pretty sure deployed GIs are still crushable in original(at least in YR), but Guardian GIs aren't in YR. Not sure what control these in original games ini code tho.

**Comment by GraionDilach** [comment]
>I'm pretty sure deployed GIs are still crushable in original(at least in YR), but Guardian GIs aren't in YR.

Exactly. http://modenc.renegadeprojects.com/DeployedCrushable was only add for the GGI.

**Comment by ABrandau** [comment]
Hm, nice to see you are back modding, this reminds me I had to go for a silly hack to get quasi GI's working on my mod. It was an Attack turreted with an invisible turret, and the firing animation was done through a muzzle anim, hope you can get it done better now.

**Comment by Mailaender** [comment]
Removed the `Crushable` TODO.

I also experimented with the muzzle, which will get the firing directions right, but not the player palette or the aiming. Didn't include it, as that won't be the proper way to fix it. The sandbag isn't just a muzzle, but a all-in-one sprite.

**Comment by Mailaender** [comment]
Updated with the `TurnsWhileImmobile` trait from https://github.com/OpenRA/OpenRA/pull/13916 by  @forcecore.

**Comment by abcdefg30** [comment]
Needs a rebase. Unfortunately we can't immediately update the engine version after the fix for OpenRA/OpenRA#12738 as we still depend on `UnitCommandWidget` which was removed upstream.

**Comment by Mailaender** [comment]
This needs to wait for https://github.com/OpenRA/OpenRA/pull/13916 to be actually commited. I assume the easiest way for `UnitCommandWidget` would be to copy a temporary of the old logic until @x-a-n-a-x or someone else crafts some UI.

**Comment by Valkirie** [comment]
This was fixed by [#14846](https://github.com/OpenRA/OpenRA/pull/14846). Can you guys move on with this one now ?

**Comment by Mailaender** [comment]
It still depends on https://github.com/OpenRA/OpenRA/issues/13285 and something that allows it to turn while immobile.

**Comment by MustaphaTR** [comment]
Closing this, i have a working GI that i'll PR soon and this is pretty old and requires rebases.

**Pull request closed without merging**
