### PR TITLE
Added Civilian Communications

### PR DESCRIPTION
**Pull request by Mailaender**
Followup of https://github.com/OpenRA/ra2/pull/114.

### CODE REVIEW

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark:

**Comment by MustaphaTR** [comment]
Wait, i already added that in that PR: #27

**Comment by abcdefg30** [comment]
Uh right, something is off here.

**Comment by Mailaender** [comment]
Not sure where we lost it.

**Comment by abcdefg30** [comment]
Seems like we lost it in https://github.com/OpenRA/ra2/commit/26599c209fbfe604c48b684d9c820e2fd2d241bf#diff-0698cbdb13927dcc62b4aee35e6d4478.

**Comment by Mailaender** [comment]
I must have confused it with a tech building and then deleted it, because I want to do them later.

**Pull request merged**
