### PR TITLE
Added Civilians

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/ra2/issues/116.

### CODE REVIEW

**Comment by GraionDilach** [comment]
You'll have to replace die3 onwards on all of them with the RA2 death effects from another infantry sequence (to give them rad, electro and whatnot deaths).

Maybe coulda even adopt a custom sequence template and inheriting that everywhere.

**Comment by Mailaender** [comment]
Updated.

**Comment by abcdefg30** [comment]
It would be nice if you could remove those `Start: 0`, `Length: 1` and `Facings: 1` junk values.
As you don't use `Defaults:` here they should be unnecessary (likewise the `Offset: 0,0` on the icons).

**Comment by Mailaender** [comment]
Removed default values.

**Comment by GraionDilach** [comment]
I noticed that `idle2` is empty at many of the sequences. Could you duplicate `idle1`/override `WithInfantryBody` to not use it?

Then this is ready to go I think.

**Comment by Mailaender** [comment]
Removed the empty `idle2`. It was probably a left-over from auto-imports, that I forgot to clean up.

**Comment by GraionDilach** [comment]
This broke Travis.

**Comment by Mailaender** [comment]
Vladimir has an `idle2` sequence as the only civilian infantry and the `Facings: 8` probably mean my sequence importers still need work.

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark:

**Pull request merged**
