### PR TITLE
Change logo.png to icon.png

### PR DESCRIPTION
**Pull request by cookgreen**
Change logo.png to icon.png

### CODE REVIEW

**Comment by abcdefg30** [comment]
Sorry, I don't think just renaming the file is the correct "fix". `logo.png` and `icon.png` have different sizes as it seems (cnc [icon.png](https://github.com/OpenRA/OpenRA/blob/f2e6601e07a73e43207bbb04f0143c63e1c60fcc/mods/cnc/icon.png), [logo.png](https://github.com/OpenRA/OpenRA/blob/f2e6601e07a73e43207bbb04f0143c63e1c60fcc/mods/cnc/logo.png)).

**Comment by abcdefg30** [comment]
I cherry-picked the `DisabledOverlay` removal onto `master` though: https://github.com/OpenRA/ra2/commit/710fbb60085be0fd5da374510e91bc05403831f1

**Comment by cookgreen** [comment]
@abcdefg30  so, shall i close this PR?

**Comment by abcdefg30** [comment]
The last commit looked fine, so I cherry-picked it onto the master branch to save you the trouble of rebasing this PR (https://github.com/OpenRA/ra2/commit/803b1b0bdcca2d3d9e3181ef8b557683e79ff8f3). Thanks!

**Pull request closed without merging**
