### PR TITLE
Destroyed trees

### PR DESCRIPTION
**Pull request by DnAp**

### CODE REVIEW

**Comment by Phrohdoh** [comment]
@DnAp Are you still working on this?

**Comment by abcdefg30** [comment]
Just looked at the original: Tanya shoots at trees and doesn't C4 them.

**Comment by DnAp** [comment]
Sorry, I was on vacation.
I will find time for look and fix it.

**Comment by abcdefg30** [comment]
> Sorry, I was on vacation.
 I will find time for look and fix it.

No problem, we're not in a hurry. :)

**Comment by DnAp** [comment]
abcdefg30 rights. I removed С4

**Comment by abcdefg30** [comment]
Looks ok to me. :+1: / :white_check_mark:

**Pull request merged**
