### PR TITLE
Fix the turret offsets of the Sentry Gun and the Patriot Missile System

### PR DESCRIPTION
**Pull request by abcdefg30**
I used those wiki pages to confirm the offsets:
http://cnc.wikia.com/wiki/Sentry_Gun_(Red_Alert_2)
http://cnc.wikia.com/wiki/Patriot_missile_system_(Red_Alert)

They might not be perfect though.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
Screenshot please.
If this looks right to you I'd say just go ahead and merge it. :+1:

**Comment by abcdefg30** [comment]
Hm, I'm not sure anymore if this is the correct way to do it, will have another look tomorrow.

**Comment by Mailaender** [comment]
Patriot missile looks way better. :white_check_mark:

**Comment by Phrohdoh** [comment]
The Patriot Missile System still looks too high to me.
Compare to the link you gave.

screen shot 2016-01-16 at 6 31 50 pm

**Comment by Iamgoofball** [comment]
I feel like the sentry gun is a little squished in, but eh

:+1:

**Comment by abcdefg30** [comment]
> Hm, I'm not sure anymore if this is the correct way to do it, will have another look tomorrow.

Doesn't look like I can do it really better. Didn't change anything now.

> The Patriot Missile System still looks too high to me. :-1:

The problem here is that the turret is too low then when facing the opposite side.

**Pull request merged**
