### PR TITLE
Added the Tech Airport

### PR DESCRIPTION
**Pull request by Mailaender**
See http://cnc.wikia.com/wiki/Tech_Airport_(Red_Alert_2) for reference.

### CODE REVIEW

**Comment by MustaphaTR** [comment]
Works fine but that would be good if you add that to maps that should have.

**Comment by Mailaender** [comment]
Do you know a map (without bridges or other unsupported stuff) that contains one?

**Comment by MustaphaTR** [comment]
Breakaway (which we already have) should have one at middle. I'm not sure about others.

**Comment by Mailaender** [comment]
Updated the Break of Day map. Looks like the civilian buildings from https://github.com/OpenRA/ra2/pull/114 and the lightning rules were missing as well.

**Comment by abcdefg30** [comment]
Looks good to me, except for the prerequisites stuff. Not sure if we can fix that with only yaml changes:
- Having both sides conyards will give you two different paratrooper powers
- (Obvious) Without a conyard you won't get anything

**Comment by GraionDilach** [comment]
Yeah, `SupportPower`s don't have faction tags which needs an upstream change to get that fixed.

**Comment by abcdefg30** [comment]
I think we can take this as is. I have a follow-up pr ready that will take care of the prerequisites issue.

**Pull request merged**
