### PR TITLE
Added the MCV transform sound

### PR DESCRIPTION
**Pull request by Mailaender**
https://gist.github.com/Mailaender/c2c5ff37a8927d0bc452#file-sound-ini-L1999

### CODE REVIEW

**Comment by GraionDilach** [comment]
This is wrong! :-1:

MoveStarts are played when the unit starts to move and they are actual motor/engine sounds.

**Comment by Mailaender** [comment]
We don't have movement sounds yet.

**Comment by Mailaender** [comment]
@pchote You were wrong btw.

**Comment by pchote** [comment]
?

**Comment by Mailaender** [comment]
Misunderstanding. Filed https://github.com/OpenRA/OpenRA/issues/10685 and https://github.com/OpenRA/ra2/pull/105.

**Pull request closed without merging**
