### PR TITLE
Added offsets for civilian buildings.

### PR DESCRIPTION
**Pull request by Mailaender**
Fixes https://github.com/OpenRA/ra2/issues/159.
Closes https://github.com/OpenRA/ra2/issues/225.

### CODE REVIEW

**Comment by Grantelbart4** [comment]
I fixed some offsets. Here is the link to the yaml file https://github.com/OpenRA/ra2/issues/225

**Comment by Mailaender** [comment]
Did you generate those automatically?

**Comment by GraionDilach** [comment]
No, those are definitely manual ones.

**Comment by Mailaender** [comment]
It undoes too many of my fixes and it isn't complete so I can't take it, sorry.

**Comment by Phrohdoh** [comment]
So, you could manually incorporate them seeing as what @Grantelbart4 has provided is perfectly in line with the purpose of this PR.

**Comment by Mailaender** [comment]
I already did that and it seemed redundant to my automatically generated changes. It is a bit unfortunate that we both worked on the same problem at the same time.

**Comment by Grantelbart4** [comment]
oh ok

**Comment by Mailaender** [comment]
As these are known to be incorrect for every building that isn't rectangular, I would prefer we use yours. Can you send a pull request yourself?

**Comment by Mailaender** [comment]
Actually scratch that. The formula for non-square buildings has been corrected.

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
Sorry, @Grantelbart4. I hope you didn't spend too much time on the offsets. (If you still spot something wrong, manual refinements are always welcome, though. :) )

**Pull request merged**
