### PR TITLE
Add more exits to gayard and nayard

### LINKED ISSUE #261: Vessel producers need more exits
It is easy to accidentally penalize yourself for something you shouldn't be penalized for.
ref #250.

screen shot 2016-07-02 at 2 44 51 pm

screen shot 2016-07-02 at 3 00 37 pm

### PR DESCRIPTION
**Pull request by Phrohdoh**
Closes #261

screen shot 2016-07-02 at 4 12 37 pm

### CODE REVIEW

**Comment by Mailaender** [comment]
It might look a bit more polished if you restrict it to NE, SE, SW and NW so the boats don't collide with the supporting pillars.

**Comment by Phrohdoh** [comment]
Are you also suggestion I remove the spawn offsets then? Those offsets will cause exactly that.

**Comment by Mailaender** [comment]
I suggest to set exits at `-2, 0`, `0,2` `4,1` and `1,4` instead.

**Comment by Mailaender** [comment]
Or wait now I understand it. You need the large exits to check for land masses. Better set the radius wider on the northern part as well if someone places it with beach head above it.

**Comment by Phrohdoh** [comment]
I don't understand.
The radius is the same all the way around, 2.

I don't see any reason it couldn't be 1 but 2 was already established so I went with that.

**Comment by Phrohdoh** [comment]
screen shot 2016-07-04 at 8 17 29 am

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark:

**Pull request merged**
