### PR TITLE
Restore the RA2 inis to extra-files.

### PR DESCRIPTION
**Pull request by GraionDilach**
Had enough of jumping back to Phrohdoh/oramod-ra2 all the time.

### CODE REVIEW

**Comment by MustaphaTR** [comment]
:+1:

**Comment by abcdefg30** [comment]
Could you elaborate why it is a good idea to store them in the repository?
As they're big files, won't change and you can easily have them locally instead.

**Comment by Mailaender** [comment]
Maybe store them elsewhere if you want to link lines like https://github.com/LipkeGu/TSIniFiles

**Comment by MustaphaTR** [comment]
@Mailaender This has no different than storing them in Phrohdoh/oramod-ra2.

**Comment by abcdefg30** [comment]
I didn't get why we want to store them at all. I (think I) won't object keeping them in here if there's a good reason.

**Comment by Phrohdoh** [comment]
I agree that these files don't need to be stored here, putting them in my repo was just an easy way to refer to them in PRs.

Perhaps wiki pages?

**Comment by GraionDilach** [comment]
I am in the middle of cleaning up the mess this mod has at weapon definitions, and the use of inheritance just makes many of the WW bogus/arbitrary eliteweapon stats more straightforward (for example Flak Trooper having a nerfed AA weapon when reaching elite).

I don't intend to balance these atm but adding comments to the appropriate RA2 line. I really don't want these comments pointing towards an artifact repository.

Wiki pages for these contents are the worst. Even a gist would be more meaningful.

**Comment by Phrohdoh** [comment]
How are wiki pages any worse than a gist?
They are both full git repos and GitHub projects directly correlate to a wiki.

**Comment by GraionDilach** [comment]
Wiki pages are technically documents with Rich Text output compared to the gist being plaintext. INI files should be plaintext.

**Comment by scshunt** [comment]
I'm opposed to this for copyright concerns. We can't put them into a GPL-licensed repository.

**Comment by GraionDilach** [comment]
Meh.

**Comment by Mailaender** [comment]
:bulb: **ProTip:** Run `OpenRA.Utility.exe ra2 --extract rules.ini` to recieve a fresh copy.

**Pull request closed without merging**
