### PR TITLE
Added Radiation

### PR DESCRIPTION
**Pull request by Mailaender**
with only minor code changes by me.

### CODE REVIEW

**Comment by sorcerer86pt** [comment]
WIll test this.

**Comment by sorcerer86pt** [comment]
Also, great number for this PR... 666 and radiation.

**Comment by sorcerer86pt** [comment]
Base Profile Screenshot 2020 03 16 - 19 42 25 24
Base Profile Screenshot 2020 03 16 - 19 42 49 57
Base Profile Screenshot 2020 03 16 - 19 42 50 97
Base Profile Screenshot 2020 03 16 - 19 43 11 35
Base Profile Screenshot 2020 03 16 - 19 43 18 79
Base Profile Screenshot 2020 03 16 - 19 44 01 66

Well nuke radiation spread is very small compared to rad guy or demo truck

**Comment by sorcerer86pt** [comment]
still needing to check nuke plant destruction

**Comment by sorcerer86pt** [comment]
Base Profile Screenshot 2020 03 16 - 19 48 18 88
Base Profile Screenshot 2020 03 16 - 19 48 24 52


Well we need to add radiation to nuke plant destruction

**Comment by Mailaender** [comment]
Added radiation to the nuclear power plant.

**Comment by sorcerer86pt** [comment]
Base Profile Screenshot 2020 03 16 - 22 33 59 59
Base Profile Screenshot 2020 03 16 - 22 34 03 96


Ok the radiation now exists, but it's instant. It should linger on some moments (for example it should kill the survivors if they stand around)

**Comment by Mailaender** [comment]
Fixed the nuke payload of the nuclear power plant explosion.

**Comment by sorcerer86pt** [comment]
ok, the nuke payload on nuclear power plant is good now 👍 

Now a silly think. The nuclear missile trail on descent:
Base Profile Screenshot 2020 03 18 - 20 27 43 15

It's not very important, but if you could only on descent modify the offset, it would be golden.
But it can be on another PR, the radiation is okay

**Comment by sorcerer86pt** [comment]
Needs rebase to fix conflict

**Pull request merged**
