### PR TITLE
Add Aircraft Carrier

### PR DESCRIPTION
**Pull request by MustaphaTR**
Currently the planes are not VTOL. But otherwise it is working pretty good.

I made all the planes have `MaximumPitch: 128` so Harrier and Beagle won't go to other side of the map to land.

Closes https://github.com/OpenRA/ra2/issues/151.

### CODE REVIEW

**Comment by MustaphaTR** [comment]
> OpenRA usually uses child/parent instead of slave/master.

I didn't name the stuff, if you want me to rename them, i can.

> Don't we only need the carrier spawner? Why are there two different traits anyway?

The BaseSpawner/Master traits handle the base stuff which will be used by V3/Dred logic. BoolBada's code also had those stuff for Angry Mob and Slave Miner, which also used those, but we don't need them here.

If you need master/slave difference, i'm not sure about that.

> There are a couple of unnecessary comments

BoolBada was a bit over the top with the comments, yeah some may be unnecessary.

**Comment by Mailaender** [comment]
This works fairly well in-game. :+1:

**Comment by sorcerer86pt** [comment]
Please rebase with master

**Comment by DylanC** [comment]
@MustaphaTR ^

**Comment by sorcerer86pt** [comment]
Okay, why can't this commit be merged in the codebase?

**Comment by GraionDilach** [comment]
Untested in this PR, but the version included in RV has an error within the code where planes above the carrier bug out when the target is destroyed and unable to enter to a stopped carrier, just fly above the entering point until the carrier is moved further and the plane can retry entering in the new place.

There are still also a good amount of coding style errors included, which are all coming from @forcecore's legacy.

For the record, I am working fairly slowly to have this codebase cleaned up for AS integration, which probably will be a better starting point for inclusion into an OpenRA repository than this current iteration is.

**Comment by MustaphaTR** [comment]
I think this can be closed since @Mailaender opened his own.

**Pull request closed without merging**
