### PR TITLE
Added Dustbowl from Yuris Revenge

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/10686.

### CODE REVIEW

**Comment by abcdefg30** [comment]
:+1: Those cows are killing my ears though. :D

**Comment by jtyle6** [comment]
@abcdefg30 yeah there are.

**Comment by destroy-everything** [comment]
I'm pretty sure I killed them all but the noise persists

**Comment by Mailaender** [comment]
If you are sure and can reproduce the error, report it as a bug via https://github.com/OpenRA/ra2/issues/new please.

**Pull request merged**
