### PR TITLE
20160116 Upgrade

### PR DESCRIPTION
**Pull request by Mailaender**
Fixes the outdated rulesets after https://github.com/OpenRA/OpenRA/pull/10371 and https://github.com/OpenRA/OpenRA/pull/10364.

### CODE REVIEW

**Comment by Mailaender** [comment]
Please ignore the checks. The configuration from https://github.com/OpenRA/ra2/pull/45 is missing here.

**Comment by abcdefg30** [comment]
Could we also introduce a `RequiresMods:` entry now?

**Comment by Mailaender** [comment]
That would be cumbersome at this stage. `make version` will change for every commit on OpenRA/OpenRA, the game won't start and the lint rules will fail.

**Comment by Mailaender** [comment]
Rebased. This will fix the build again.

**Comment by abcdefg30** [comment]
:+1:

**Pull request merged**
