### PR TITLE
Added support for installing this into the support folder

### PR DESCRIPTION
**Pull request by Mailaender**
See https://github.com/OpenRA/OpenRA/pull/10232. Had to fix several unrelated things to get this to run.

Fixes https://github.com/OpenRA/ra2/issues/13.
Fixes https://github.com/OpenRA/ra2/issues/31.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
> The latest development version...

Doesn't fly at all. Instead you should use a hash that you know it works on.
That was part of the entire reason for supporting support mods (requires: git-123456).

**Comment by Mailaender** [comment]
Maybe for releases, but not for development.

**Comment by Phrohdoh** [comment]
Yes, for both.
This way you know what others have updated to (you know what is/isn't supported) and you know what not to add.

**Comment by Mailaender** [comment]
Now also takes the revert from https://github.com/OpenRA/OpenRA/pull/10486 into consideration.

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark: 
But needs a rebase.

**Comment by Mailaender** [comment]
Rebased.

**Comment by abcdefg30** [comment]
Sorry all other guys, we need to get this in, it's just a PITA to run the mod otherways at the moment. You need to use https://github.com/OpenRA/OpenRA/pull/10482 as OpenRA version for now, since "normal" OpenRA has a bug crashing this mod.

**Comment by Mailaender** [comment]
I like the idea of developing against a set version of the OpenRA engine and CI test this with the engine from DEBs installed although that will be slightly boring and slow down progress a lot. My suggestion would be master/next/bleed (stable/playtest/bleed) as branches if we can keep up with the additional overhead of maintaining 3 branches.

**Comment by Phrohdoh** [comment]
I highly suggest against more than a single branch as we've hardly been able to handle that so far.
A single `master` that is set against the latest upstream `release-` is the best way forward in my opinion.

**Comment by abcdefg30** [comment]
I think at least to branches would be good. Only relying on the release will slow down progress a lot (e.g. we have to wait for a new release until a required upstream feature can be used) and it'll also be really not too convenient to update huge chunks of the mod at once (when a new release is tagged) instead of doing small but steady updates.

**Comment by Mailaender** [comment]
We could transition to developing against a playtest soon and a release afterwards I guess.

**Pull request merged**
