### PR TITLE
Fix Defences' wrong Inherits:

### PR DESCRIPTION
**Pull request by MustaphaTR**
Moved Phrohdoh/OpenRA#76 to here.

#1 had to be splited anyway. This can be deleted from there.

### CODE REVIEW

**Comment by abcdefg30** [comment]
`gagap` probably wants an `-AutoTarget:` then.

**Comment by MustaphaTR** [comment]
Updated.

**Comment by MustaphaTR** [comment]
In fact AAs are also not Auto Targeted in orginal games but not sure should i change this here, it always looked like bug to me.

**Comment by abcdefg30** [comment]
> In fact AAs are also not Auto Targeted in orginal games but not sure should i change this here, it always looked like bug to me.

That has to be a bug. For me they always auto targeted.

**Comment by abcdefg30** [comment]
:+1:

**Pull request merged**
