### PR TITLE
Redesigned radar logos (using Affinity Designer).

### PR DESCRIPTION
**Pull request by ShikiSuen**
Coping with https://github.com/OpenRA/ra2/issues/637#issuecomment-590462419
Copyright: Shiki Suen (Feb 25th, 2020)
Radar logo project files commited together, requiring Affinity Designer to open and edit them.

[Update: Feb 27, 2020]

image
image
image

-------------
I checked tomsons26's new radar logo. They look too metalic / material-style which (my personal opinion) are not something self-luminescent. These logos may have better places to use (like the menu select of campaign missions, etc.).

Anyway, just now I use Affinity Designer to recreate radar logos for all three fractions.
Since Affinity Designer documents are all vectors, they can be resized as much as you wish.
(I will share the original project files of these logos. It is you people's matter to buy Affinity Designer.)

See https://github.com/OpenRA/ra2/issues/637#issuecomment-590872724

### CODE REVIEW

**Comment by ShikiSuen** [comment]
Wait on a sec. Allied logo has lack of one layer effect.

**Comment by ShikiSuen** [comment]
File update complete.

**Comment by CDVoidwalker** [comment]
Imo change the hammer and sickle to look more like [this](https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Hammer_and_sickle.svg/1024px-Hammer_and_sickle.svg.png) as the one you proposed is rather unappealing (at least to me).

**Comment by CDVoidwalker** [comment]
> (I will share the original project files of these logos. It is you people's matter to buy Affinity Designer.)

You should rather make it in some open source software, this way it can actually be accepted as I highly doubt anyone is willing to do that

**Comment by ShikiSuen** [comment]
> > (I will share the original project files of these logos. It is you people's matter to buy Affinity Designer.)
> 
> You should rather make it in some open source software, this way it can actually be accepted as I highly doubt anyone is willing to do that

You can sign up for trial of Affinity Designer. It is much more comfortable to use comparing to Adobe Illustrator CC, for anyone who already get used to Adobe Photoshop.

Unless you are on GNU Linux, then I guess that Inkscape is the way to go.
---

Anyway, I am gonna pause this PR until I introduce a new shaped design in the Allied Logo.
(https://github.com/OpenRA/ra2/issues/637#issuecomment-591558009 does not want to admit that my existing Allied logo reworks are "traced" but insists that they are "ripped", regardless that what he wants to support are all "traced" works.)

**Comment by ShikiSuen** [comment]
@CDVoidwalker The shape of the Hammer and Sickle is:
image

and is from:
image

**Comment by ShikiSuen** [comment]
image
image
image

**Comment by ShikiSuen** [comment]
@Mailaender Please state if you are surely not going to review this. In that case, since I don't know how to change the specified reviewer, I may have to close this PR and create a new one specifying another reviewer.

P.S.: My new designs this time got good feedbacks on Facebook:
https://www.facebook.com/groups/548634081837131/permalink/3108160105884503/

**Comment by Metadorius** [comment]
I don't know how oblivious one should be to not be able to see through that "good feedback" given to a misleading post. Also it looks like you're trying to bypass Mailaender who most likely won't accept the PR with this request you wrote in hopes of other reviewer letting this through.

**Comment by Metadorius** [comment]
Oh, and stop advertising Affinity Designer, please.

**Comment by ShikiSuen** [comment]
@Metadorius There is no free competitive software comparing to Affinity Designer. I tried Inkscape but found no way to achieve the same results.

**Comment by ShikiSuen** [comment]
Closing this PR now. Too much trash commit histories.

**Pull request closed without merging**
