### PR TITLE
Added missing Debug overlays

### PR DESCRIPTION
**Pull request by Mailaender**
to help investigate #150 and Z-Offset issues.

### CODE REVIEW

**Comment by sorcerer86pt** [comment]
Okay tested it. Custom terrain debug works BUT Depth data doesn't. All i got is a blue scree (not fo death)
Base Profile Screenshot 2020 03 17 - 18 15 05 71
Base Profile Screenshot 2020 03 17 - 18 15 13 90
Base Profile Screenshot 2020 03 17 - 18 15 59 13
Base Profile Screenshot 2020 03 17 - 18 16 05 40

**Comment by Mailaender** [comment]
That's exactly what https://github.com/OpenRA/ra2/pull/675 is for.

**Comment by Mailaender** [comment]
Also that is not the custom terrain debug overlay you screenshoted there.

**Comment by sorcerer86pt** [comment]
I know, but that overlay is working. I saw labels for gold and gems, for
example.

**Pull request merged**
