### PR TITLE
Added civilian building husks

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/ra2/issues/240.

### CODE REVIEW

**Comment by MustaphaTR** [comment]
Should we call them as Husk here? They are called as Rubble in original game.

Code looks fine but we need to check if you added rubble for something rubbleless first. Some buildings doesn't have one.

**Comment by Phrohdoh** [comment]
Does `^CivBuildingHusk` need `AutoSelectionSize` (inherited from `^SpriteActor`)?

I'm behind the idea of renaming husk to rubble here (and then dead->rubble in the sequences) but that isn't absolutely necessary.

Could actors walk over rubble in vanilla RA2? (I've not had any luck running the game via Wine)
Other than those little nits, this is very cool. Looks good ingame.

screen shot 2016-06-30 at 12 25 45 pm

**Comment by MustaphaTR** [comment]
Units can walk over Rubbles in vanilla RA2. Rubbles also shouldn't have a selection box.

**Comment by Phrohdoh** [comment]
They aren't selectable with this PR.

**Comment by Mailaender** [comment]
`AutoSelectionSize` is required for the rendering bounds only. The trait name is a bit misleading. It has nothing to do with selection boxes.

I renamed everything to rubble and allowed units to walk over it.

**Comment by abcdefg30** [comment]
`Exception of type 'System.InvalidOperationException': Unit 'carus02g' does not have a sequence named 'rubble'`

**Comment by abcdefg30** [comment]
Looks quite fine otherwise, but not sure how many more actors are affected by the crash.

**Comment by Mailaender** [comment]
Fixed. The problem occurs when TEMPERAT and SNOW sequences don't match.

**Comment by abcdefg30** [comment]
Looks good to me now. 👍

**Pull request merged**
