### PR TITLE
Added support for C&C The Ultimate Collection

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/ra2/issues/245.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
@Mailaender How did you test this?

**Comment by Mailaender** [comment]
With a Windows 7 Origin installation from the 2015 Freeware promotion http://www.pcgamer.com/command-conquer-red-alert-2-is-free-on-origin/

**Comment by abcdefg30** [comment]
Works nicely. Thanks. :) 👍 / ✅

**Comment by Mailaender** [comment]
I tried to set this up as generic as possible. If this doesn't work with the US English version (Origin enforces a localized install) then we need another entry and call this one German.

**Pull request merged**
