### PR TITLE
Added the Tech Hospital

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/ra2/issues/270#issuecomment-230362189.

### CODE REVIEW

**Comment by MustaphaTR** [comment]
This is unnecessary. You remember the compression link u gave. UIName= is whar matters not Name=. 

If you are not gonna edit rubble/debris don't add it at all.

**Comment by Phrohdoh** [comment]
This is not unnecessary.
If someone has used this actor we should support that.

**Comment by MustaphaTR** [comment]
Maybe noy unnecessary,  but wrong. As i said they both have same ingame name.

**Comment by Phrohdoh** [comment]
@Mailaender Could you remove `Tooltip` from this so we can get this merged?

**Comment by Mailaender** [comment]
I believe it makes sense to differentiate via the tooltip in both the map editor and in-game.

**Comment by Phrohdoh** [comment]
Is there really any difference though?
They seem to serve the same purpose (if the new one serves any purpose at all).

The tooltip in the map editor will show `cathosp` so it differentiates already.

**Comment by MustaphaTR** [comment]
Agreed with @phrohdoh . Codename is already shown pn editor.

**Comment by Mailaender** [comment]
I changed it to `EditorOnlyTooltip` now.

**Comment by Phrohdoh** [comment]
That in no way addresses applying a new name that the original didn't have to the actor.

**Comment by abcdefg30** [comment]
I think it's a good idea. Mappers might wonder why the hospital is "duplicated". They would need to look the differences in the rules between those two up anyways (to see if there any, and if yes which), both with and without a tooltip.

**Comment by abcdefg30** [comment]
Hm, I just discovered that there is a `cathosp.shp`. Maybe we can use that (although the original didn't)?

**Comment by GraionDilach** [comment]
cathosp.shp was never used in the actual game, being an unfinished asset (lacking damage frame, has a mess at palettes, with citytem.pal being used for snow and citysno.pal used for temperate IIRC, etc).

**Comment by abcdefg30** [comment]
Ah well, seems like I accidently had the wrong palette selected when discovering the shp. Thanks anyway.

So, this looks fine to me now. 👍 / ✅

**Pull request merged**
