### PR TITLE
Update the mod to use map format 9

### PR DESCRIPTION
**Pull request by abcdefg30**
Also let the utility remove the new lines it doesn't like. We should just avoid adding them again.

### CODE REVIEW

**Comment by abcdefg30** [comment]
OpenRA\OpenRA#10839 just got merged and bumped the format to `10`. Will update this tomorrow.

**Comment by pchote** [comment]
Some of the format 10 updater changes will be reverted, so you should hold until that gets sorted.

**Comment by abcdefg30** [comment]
Updated.

**Comment by abcdefg30** [comment]
Merging with the :+1: of @Phrohdoh.

**Pull request merged**
