### PR TITLE
Enabled per-pixel depth calculations

### PR DESCRIPTION
**Pull request by Mailaender**
Incorporate changes from:

* https://github.com/OpenRA/OpenRA/pull/11124 with the help of https://github.com/OpenRA/OpenRA/pull/17720
* https://github.com/OpenRA/OpenRA/pull/11904/
* https://github.com/OpenRA/OpenRA/pull/11091
* https://github.com/OpenRA/OpenRA/pull/11572

### CODE REVIEW

**Comment by sorcerer86pt** [comment]
hoe one can test this?

**Comment by Mailaender** [comment]
Check if terrain properly hides units behind it. You will notice it does that only on this branch. Also check that all sprite actors (buildings, infantry) are still fully visible as that might have regressed.

**Comment by sorcerer86pt** [comment]
well i found that there are some visibility artifacts

Base Profile Screenshot 2020 03 17 - 18 03 10 00
Base Profile Screenshot 2020 03 17 - 18 03 16 94
Base Profile Screenshot 2020 03 17 - 18 03 19 25
Base Profile Screenshot 2020 03 17 - 18 03 53 16
Base Profile Screenshot 2020 03 17 - 18 03 54 37
Base Profile Screenshot 2020 03 17 - 18 03 55 22
Base Profile Screenshot 2020 03 17 - 18 05 19 71
Base Profile Screenshot 2020 03 17 - 18 05 21 74

**Comment by Mailaender** [comment]
Fixed allied refinery, weapons factory, airport and the repair cranes. Also fixed all RA2 engine weapon effects.

**Comment by Mailaender** [comment]
Rebased.

**Comment by sorcerer86pt** [comment]
Base Profile Screenshot 2020 03 18 - 20 16 00 24
Base Profile Screenshot 2020 03 18 - 20 20 26 52
Base Profile Screenshot 2020 03 18 - 20 20 52 07

**Comment by Mailaender** [comment]
Rebased, fixed tech buildings and allied service depot.

**Comment by sorcerer86pt** [comment]
Allied structures and some cliffs:

Base Profile Screenshot 2020 03 19 - 10 47 18 69
Base Profile Screenshot 2020 03 19 - 10 47 28 85
Base Profile Screenshot 2020 03 19 - 10 47 34 81
Base Profile Screenshot 2020 03 19 - 10 47 38 96
Base Profile Screenshot 2020 03 19 - 10 47 49 47
Base Profile Screenshot 2020 03 19 - 10 47 57 43

**Pull request merged**
