### PR TITLE
Fixed Allied MCV and Chrono Miner voices

### PR DESCRIPTION
**Pull request by Mailaender**
https://gist.github.com/Mailaender/c2c5ff37a8927d0bc452#file-sound-ini-L1642

### CODE REVIEW

**Comment by GraionDilach** [comment]
What is the point of this? Most vehicles had a shared voice in RA2, YR added separate vehicle voices.

**Comment by Mailaender** [comment]
Apparently MCV and chrono miner already had some move sounds.

**Comment by MustaphaTR** [comment]
Move sound i think should go to its own trait. They are sound, not voice.

**Comment by Mailaender** [comment]
But this is about the voice, not the movement sound.

**Comment by GraionDilach** [comment]
Yes, which is still the same, so comes back to my initial question: what's the point of this?

**Comment by Mailaender** [comment]
It corrects the allied MCV and chrono miner voice sets which aren't generic (at least for Move).

**Comment by GraionDilach** [comment]
Ah, moa and moc aren't used there. Dammit, took me a while. :+1: then.

**Comment by abcdefg30** [comment]
:+1:

**Pull request merged**
