### PR TITLE
Fix crash with Apoc vs Rocketeers

### LINKED ISSUE #38: Apocalipsis tank kills jumpjet
```
Red Alert 2 Mod at Version {DEV_VERSION}
on map cb142fef4b80694b59ba09010a34ca335e5e2f6c (allied-02 by Westwood Studios).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Unit `jumpjet` does not have a sequence named `die3`
   в OpenRA.Graphics.SequenceProvider.GetSequence(String unitName, String sequenceName) в d:\Games\OpenRA-bleed\OpenRA.Game\Graphics\SequenceProvider.cs:строка 65
   в OpenRA.Graphics.Animation.GetSequence(String sequenceName) в d:\Games\OpenRA-bleed\OpenRA.Game\Graphics\Animation.cs:строка 205
   в OpenRA.Graphics.Animation.PlaySequence(String sequenceName) в d:\Games\OpenRA-bleed\OpenRA.Game\Graphics\Animation.cs:строка 86
   в OpenRA.Graphics.Animation.PlayThen(String sequenceName, Action after) в d:\Games\OpenRA-bleed\OpenRA.Game\Graphics\Animation.cs:строка 120
   в OpenRA.Mods.Common.Effects.Corpse..ctor(World world, WPos pos, String image, String sequence, String paletteName)
   в OpenRA.Mods.Common.Traits.WithDeathAnimation.<>c__DisplayClass1.<SpawnDeathAnimation>b__0(World w)
   в OpenRA.World.Tick() в d:\Games\OpenRA-bleed\OpenRA.Game\World.cs:строка 309
   в OpenRA.Game.InnerLogicTick(OrderManager orderManager) в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 557
   в OpenRA.Game.LogicTick() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 582
   в OpenRA.Game.Loop() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 709
   в OpenRA.Game.Run() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 749
   в OpenRA.Program.Run(String[] args) в d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:строка 117
   в OpenRA.Program.Main(String[] args) в d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:строка 39
```

### PR DESCRIPTION
**Pull request by MustaphaTR**
Fixes  #38. It was possibly wrong because it was copy-pasted from TS mod.

### CODE REVIEW

**Comment by abcdefg30** [comment]
I'm not convinced that this is the correct solution. E.g. the elite weapon of the soviet harvester uses `DeathType3` still too (that will crash on dogs, iirc).

I think the real cause here is that we should fix the rocketeer using death types. It should have only one "die-in-air" animation.

In addition the `TriggerProne` types don't make sense, as they are on a `ValidTargets: air` warhead and rocketeers shouldn't go prone.

**Comment by MustaphaTR** [comment]
No unit have a `Die3:`, not sure why it causes crash only vs dogs and rocketeers. But you are right about prone i think.

**Comment by MustaphaTR** [comment]
I'm not sure what DeathType3 is but i think it might be killing unit directly with no anim. Even if that might be it, we need to change it's name, DeathType3 has no meaning unlike others.

**Comment by abcdefg30** [comment]
> No unit have a `Die3:`

Oh, hm, I just remembered dogs because they have `die3` out-commented. Just remove the `DamageTypes` from `MammothTusk` then, please. Also remove `DeathType3` from all other places, please: [20mmrapidE](https://github.com/OpenRA/ra2/blob/c49cd160d003c09896883f1fc9b258dd5cf03fb4/weapons.yaml#L276), [DeathSounds@normal](https://github.com/OpenRA/ra2/blob/e88573c5b5c5e9cc6ac2ce24cd90dc98ab6b02a6/rules/defaults.yaml#L303) and [WithDeathAnimation@normal](https://github.com/OpenRA/ra2/blob/e88573c5b5c5e9cc6ac2ce24cd90dc98ab6b02a6/rules/defaults.yaml#L273).

While you're at it, could you remove the out-commented `die3` variants of the dogs too, please?

**Comment by MustaphaTR** [comment]
Mammoth Tusk have `InfDeath=2` not 3. https://github.com/Phrohdoh/oramod-ra2/blob/master/extra-files/rules.ini#L19219

But 20mmRapidE's is 3 is `InfantryExplode=` which is set to `S_BANG34` ,an explosion. I think there is where unused `infdie.shp` for.

**Comment by MustaphaTR** [comment]
Is that all i want to be sure before squash?

**Comment by abcdefg30** [comment]
Yaml changes look good to me.

**Comment by GraionDilach** [comment]
Looks good, merge it after squash imo.

**Comment by MustaphaTR** [comment]
Squashed but left removal of `die3:` dog's commit seperate. It is not realls about the crash.

**Comment by abcdefg30** [comment]
> Looks good, merge it after squash imo.

Did a quick ingame test first. ;)
Anyway, yaml looks good. :+1: 
And it doesn't crash ingame. :white_check_mark:

**Comment by yaaaaa** [comment]
Coool, How fast =) Now I can try to play the full match)

**Comment by Phrohdoh** [comment]
Awesome job guys. :smile:

**Pull request merged**
