### PR TITLE
Added swim animations to Tanya and the NAVY Seal

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/ra2/issues/142.

### CODE REVIEW

**Comment by GraionDilach** [comment]
This has an issue though, it does not affect `Targetable`, which will mean that units which are only capable of attacking water targets, (Subs, squids, dolphins) will be unable to attack it.

So it might be better if instead of a sequence modifier trait, this will be a "grant-upgrade-if-in-water" trait and the let `WithInfantryBody` and `Targetable` be upgraded with it.

**Comment by Mailaender** [comment]
`WithInfantryBody` is upgradeable, but not `WithDeathAnimation` so I keep doing it with infantry modifiers for now which is simple and robust. I added an upgrade type for underwater targeting though.

**Comment by GraionDilach** [comment]
Nice, since it keeps the Ground targeting in water, that resolves my gameplay issue with it, I'm fine with the infantry sequences visually looking odd then for now.

Notsure if I should wait from a confirmation of @abcdefg30 here with the merging - the :+1: is granted.

**Comment by Mailaender** [comment]
Not sure if we have enough review capacity for a +2 system. I plan to further work on improvements, but that would be OpenRA upstream, not this pull request.

**Comment by GraionDilach** [comment]
On a second thought, I agree. Death animations are a mess anyway. Good job on this regardless.

**Pull request merged**
