### PR TITLE
Update make.ps1

### PR DESCRIPTION
**Pull request by Walkman100**
Allow loading the dependency folder from the command line
This allows running the `make` powershell file completely automated:
```posh
make dependencies "path\to\OpenRA"
```
I'm using this in a [script](https://github.com/Walkman100/OpenRA-Install-Guide/blob/master/Install-RA2/InstallRA2.bat) I have that automatically clones & builds OpenRA and this mod, and currently the user has to [copy & paste](https://github.com/Walkman100/OpenRA-Install-Guide/blob/master/Install-RA2/InstallRA2.bat#L21) the file path that the script outputs into the powershell input.
It would be awesome to be able to do this automatically.

Tested on Win7x64

---
This change is [Reviewable](https://reviewable.io/reviews/openra/ra2/210)

### CODE REVIEW

**Comment by GraionDilach** [comment]
Thank you for this pull request.

I am unsure about this being redundant, though. You see, the short-midterm plan is to revamp the infrastructure a bit with #209, which would ease up and fix a lot of the overhead and missing automation of our makefiles, thereby allowing to simplify your own build script by dropping out the workarounds to counter ours (like automatically getting the right upstream version and whatnot) but it seems that the upstream dependency got stuck which might mean #209 might not arrive soon.

In any case, I leave my :+1: here, and leave the decision to merge this to @Mailaender  or @abcdefg30.

**Comment by Mailaender** [comment]
Why not, but I can't test on Linux.

**Comment by GraionDilach** [comment]
This needs a rebase now, sorry.

**Comment by Walkman100** [comment]
Done (actually just reset --hard and cherry-picked my commit)

[Walkman100:patch-1](https://github.com/Walkman100/ra2/tree/patch-1) shows the change exactly as I'd want it to show up here, but the PR hasn't updated. Do I need to send a new PR? I haven't come across this before...

**Comment by GraionDilach** [comment]
Apparently you do, this was the first time I've seen a full history rewrite myself as well.

**Comment by Mailaender** [comment]
Yeah sorry, you need to create a new pull request. This was automatically closed as I force pushed some missing git history in as it seems. Sadly the creation of this repository and the previous ones wasn't exactly complete.

**Pull request closed without merging**
