### PR TITLE
Added a pre-release warning

### PR DESCRIPTION
**Pull request by Mailaender**
like https://github.com/OpenRA/OpenRA/pull/12369.

### CODE REVIEW

**Comment by pgwipeout** [comment]
A bloody impressive work in progress.

The updates in the last few weeks have brought it to the point of being quite playable.

**Comment by Mailaender** [comment]
We will probably be able to ship Red Alert 2 before Tiberian Sun as it has less convoluted engine requirements. Still a lot to do here.

**Comment by pgwipeout** [comment]
True, but there appears to be some overlap (height map comes to mind).

My knowledge of .net is non existent so I can't really assist with code, but I'm happy to keep on testing.

**Comment by sorcerer86pt** [comment]
How to check this warning?

**Comment by Mailaender** [comment]
Type `make version` and start the game.

**Comment by sorcerer86pt** [comment]
well they can be warned now :-) 
Base Profile Screenshot 2020 03 17 - 19 31 10 39

**Comment by sorcerer86pt** [comment]
we should also if possible create a list of know bug/ missing features

**Comment by Mailaender** [comment]
That is what https://github.com/OpenRA/ra2/issues is for.

**Pull request merged**
