### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by x-a-n-a-x**
Added a step-by-step installation tutorial for Windows users.

### CODE REVIEW

**Comment by Mailaender** [comment]
Add it to the https://github.com/OpenRA/ra2/wiki instead.

**Comment by x-a-n-a-x** [comment]
I have created this wiki page : 
https://github.com/OpenRA/ra2/wiki/How-to-get-the-RA2-mod-in-OpenRA-(bleed),-under-Windows

**Comment by penev92** [comment]
Why the wiki?

**Comment by Mailaender** [comment]
To have documentation at one place, keep it editable, etc.

**Pull request closed without merging**
