### PR TITLE
Added SpawnSurvivors

### PR DESCRIPTION
**Pull request by Mailaender**
However, I removed the redundancy towards `SpawnActorsOnSell`.

### CODE REVIEW

**Comment by MustaphaTR** [comment]
Current yaml setup makes it so the game checks for the actual faction of the building while selling but use the matching faction with the building on destruction. Altho this shouldn't matter in a normal game unless you get an MCV of other faction from a crate, it is an unnecessary inconsistency.

**Comment by sorcerer86pt** [comment]
okay, both destroying and selling spawn survivors.
For example soviet mcv sell/destroyed spawns 1 eng, 7 concripts, while allied spawns 1 eng, 4 GIs

**Comment by Mailaender** [comment]
Conscripts are cheap.

**Comment by sorcerer86pt** [comment]
I know, and it's perfectly okay. I was saying that because it's a
confirmation that what is described in the yaml file is being successfuly
spawned. And since conyard is the one with engineer and basic infantry, I
used it as example

**Pull request merged**
