### PR TITLE
Added ChronoshiftableWithSpriteEffect

### PR DESCRIPTION
**Pull request by Mailaender**
Starts tackling https://github.com/OpenRA/ra2/issues/557.

### CODE REVIEW

**Comment by sorcerer86pt** [comment]
Just remember that Chrono legionnaires in OG Ra2 can be chronosphered successfully (exception to major support powers killing infantary on use)

**Comment by Mailaender** [comment]
You are right that the bubble is still missing. That might need an engine update.

**Comment by Mailaender** [comment]
Okay. Done.

**Comment by sorcerer86pt** [comment]
ok, finished testing it. It looks good. the z-offset make the effect going directly down on the vehicles.

**Pull request merged**
