### PR TITLE
Added soviet ballistic missiles

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/ra2/issues/118
Closes https://github.com/OpenRA/ra2/issues/696

### CODE REVIEW

**Comment by sorcerer86pt** [comment]
gonna test this one: -)

**Comment by sorcerer86pt** [comment]
OK, in terms of basic functionality and damage values it looks ok. 
BUT in terms of aesthestics and overall missile behaviour it still needs some work:

1. Missile needs the launch animation and sound (that small wait time to launch and whoosh)
2. Missile needs a more steeper/vertical curve, they look like a slingshot projectile, not a vertical launch missile

Lastly og RA2 dreadnought behaviour was to wait for the 2 missiles to be reloaded to launch. This can be a gameplay functionality (less wait time but less overall damage). 

Base Profile Screenshot 2020 04 23 - 11 58 50 78
Base Profile Screenshot 2020 04 23 - 11 58 35 96

[V3 launch](https://drive.google.com/file/d/1ZMoG9zV_x0XD_41Xa-KsG6o7Y2sZCBF2/view?usp=sharing)
[Dreadnought](https://drive.google.com/file/d/1iAJwy2k8E4gWMRRGlKy2DOeiCpRiiMNz/view?usp=sharing)

**Comment by Mailaender** [comment]
Added the launch sounds and improved the Dreadnought firing all missiles at once. The launch animation which tilts the missile and the steeper pitch need an engine update or rather several.

**Comment by sorcerer86pt** [comment]
How so? What is needed on engine to make that work, so we can build a issue?

**Comment by Mailaender** [comment]
Something like https://github.com/OpenRA/OpenRA/pull/17796.

**Comment by Mailaender** [comment]
Added the v3 launch animation.

**Comment by sorcerer86pt** [comment]
Checked now:

- Sounds and missile tail animation for V3 is good
- Dreadnought missile sound and tail animation is good
- Dreadnought now shots the 2 missiles

Noticed one other thing, in OG ra2 Tanya and other commandos that use C4 could use them to destroy Dreadnoughts in one go (In fact the first allied mission used that to bump Tanya to elite status). At the moment she attacks normally, not using the C4

[V3 launch](https://drive.google.com/file/d/1Dn9L5si9IHZbQCLNWIQ-ipEtCmH4PGdw/view?usp=sharing)

[Dreadnought launch](https://drive.google.com/file/d/1ZKL6gQiA2lzCiI0oCvWiBTa1wHHrhFqh/view?usp=sharing)

**Comment by pgwipeout** [comment]
Is it just me or do those missiles fly a lot faster than original.
Is it possible to get the acceleration affect from the original?

**Comment by Mailaender** [comment]
Added C4 demolition to all ships.

**Comment by Mailaender** [comment]
Fixed.

**Comment by sorcerer86pt** [comment]
It looks good to me. When a C4 unit targets Dreadnought or Aircraft carrier, the cursor changes to C4 cursor and after 1 second the units is destroyed.

**Comment by Mailaender** [comment]
Added acceleration to the missiles and fixed the Dreadnought not requiring to face the targets.

**Comment by sorcerer86pt** [comment]
The following exception occurred when testing the dreadnought.

OpenRA engine version release-20200202
Red Alert 2 mod version {DEV_VERSION}
on map 7c8e7a330adc911200225027aa2ce111971fe629 (Tsunami by Westwood Studios).
Date: 2020-04-28 10:36:10Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IndexOutOfRangeException`: Índice fora dos limites da matriz.
   em OpenRA.Map.GetTerrainIndex(CPos cell)
   em OpenRA.Map.GetTerrainInfo(CPos cell)
   em OpenRA.Mods.Common.Traits.Render.LeavesTrails.OpenRA.Traits.ITick.Tick(Actor self)
   em OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   em OpenRA.World.Tick()
   em OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   em OpenRA.Game.LogicTick()
   em OpenRA.Game.Loop()
   em OpenRA.Game.Run()
   em OpenRA.Game.InitializeAndRun(String[] args)
   em OpenRA.Program.Main(String[] args)

I think it was when the missiles were launched and it was still visible, but then the kirov that was giving vision died, and no more vision when launching.

**Comment by Mailaender** [comment]
I already fixed it in https://github.com/OpenRA/OpenRA/pull/17965. The engine here is outdated.

**Comment by sorcerer86pt** [comment]
Can you update the engine in the pull request?

**Comment by Mailaender** [comment]
No.

**Comment by sorcerer86pt** [comment]
This branch needs to be rebased and conflicts resolved

**Comment by Mailaender** [comment]
Rebased.

**Comment by MustaphaTR** [comment]
This could use a rebase too, it is still on previous engine version. And the balistic missile code in RV has been updated since to include proper take off which seems to be missing here. The ones [on the custom engine](https://github.com/MustaphaTR/OpenRA/tree/rv-engine/OpenRA.Mods.AS/Traits), old code is still kept on RV's SDK level dll for easter egg unit that still catapults the missile.

This could also include Vladimir's Dreadnought campaign unit, while you are in it.

**Comment by Mailaender** [comment]
The rebase is quite huge and I don't have proper IDE support for legacy .NET so I am closing this.

**Pull request closed without merging**
