### PR TITLE
Added the Tiberian Sun cameo palette

### PR DESCRIPTION
**Pull request by Mailaender**
This is helpful when digging through the left-overs in the asset browser.

### CODE REVIEW

**Comment by GraionDilach** [comment]
In this case, I'd add the TS anim.pal as well into this - s_clsn42 uses that.

**Comment by MustaphaTR** [comment]
Power down anim also uses anim.pal iirc, but maybe palette.pal not sure. Adding that would be good too.

**Comment by GraionDilach** [comment]
Palette.pal is shared between the two being the RA1 temperat.pal.

**Comment by MustaphaTR** [comment]
I looked to Ares.dll Documentation, it says togle power uses mousepal.pal.

**Comment by Mailaender** [comment]
I filed https://github.com/OpenRA/ra2/pull/63 for the TS mousepal.pal fix.

**Comment by abcdefg30** [comment]
Looks good to me.

**Pull request merged**
