### PR TITLE
Fix Auto Targeting

### PR DESCRIPTION
**Pull request by MustaphaTR**
Engine version here doesn't look like has Assault Move yet. But this doesn't crash anything and i don't really wanna define them again for Assault Move later.

Also depends on #429.

### CODE REVIEW

**Comment by Mailaender** [comment]
Needs a rebase.

**Comment by LinuxDonald** [comment]
@MustaphaTR have you maybe please the time for an rebase on this? :)

**Comment by MustaphaTR** [comment]
This needs ifv PR to me merged first. That's why i haven't rebased it yet.

**Comment by MustaphaTR** [comment]
Updated.

**Comment by MustaphaTR** [comment]
Rebased.

**Comment by DylanC** [comment]
@Mailaender - Rebased! 🎉

**Comment by Mailaender** [comment]
Does the engine now have assault move?

**Comment by MustaphaTR** [comment]
Yes, Engine is on lastest release now.

**Pull request merged**
