### PR TITLE
Make ra2 compatible with {DEV_VERSION}

### PR DESCRIPTION
**Pull request by cookgreen**

### CODE REVIEW

**Comment by Mailaender** [comment]
Not sure what you are trying to achieve here, but you can't just update the rules without updating the engine version in `mod.config`.

**Comment by abcdefg30** [comment]
Seems like this wants to update the engine of the mod indeed. I've already started this task myself last weekend in https://github.com/abcdefg30/ra2/commit/48c0a922bf83c38286bda7b5a75bababa8e8cc16. That however has still some issues I need to investigate, like sounds not working anymore.

**Comment by cookgreen** [comment]
@Mailaender Well, what i have done is remove some traits that OpenRA noticed not exist anymore, and it seems like you guys add some hardcoded traits that mod must give like `GivesBuildableArea`
And I add a Soviet Mission for ra2, if you guys didn't like it, I will remove it from this PR.

**Comment by cookgreen** [comment]
@abcdefg30 How did you guys calculate the OpenRA Engine version?

**Comment by cookgreen** [comment]
@Mailaender done

**Comment by Mailaender** [comment]
Let's go with https://github.com/OpenRA/ra2/pull/459 instead.

**Pull request closed without merging**
