### PR TITLE
Fixed the primary building rendering

### PR DESCRIPTION
**Pull request by Mailaender**
Basically https://github.com/OpenRA/OpenRA/pull/11565/ adapted for RA2. Fixes https://github.com/OpenRA/ra2/issues/181.

### CODE REVIEW

**Comment by MustaphaTR** [comment]
I didn't test but i think this renders them like in TS and this is not the true way to go because RA2 primary/power text is different. Gimme a sec to find an image.

**Comment by MustaphaTR** [comment]
This is power one but it is similar: https://github.com/OpenRA/OpenRA/issues/6011

**Comment by Phrohdoh** [comment]
I agree that implementing the banner would be nice (possibly an addition to `WithTextDecoration`) but this looks good enough, so 👍.

screen shot 2016-07-05 at 8 37 26 am

**Comment by MustaphaTR** [comment]
This looks fine for now so :+1: from me too. We may need to open an issue to discuss about the banner.

**Pull request merged**
