### PR TITLE
Fix Metadata for the Installer

### LINKED ISSUE #296: ra2 mod crashes when configuring assets
Hi guys,

I'm trying to run the ra2 mod, i get to the main menu, which has the ra2 icon, but when i try to configure the content, the game crashes. Exception logs says:

Mod Chooser Mod at Version {DEV_VERSION}
Date: 2016-09-11 10:08:10Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34014
Exception of type `System.Reflection.TargetInvocationException`: Exception has been thrown by the target of an invocation.
Inner Exception of type `System.IO.FileNotFoundException`: File not found: ra2
     at OpenRA.FileSystem.FileSystem.Open(String filename) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\FileSystem\FileSystem.cs:line 228
   at OpenRA.MiniYaml.<>c__DisplayClass28.<Load>b__27(String s) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\MiniYaml.cs:line 390
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at OpenRA.MiniYaml.Merge(IEnumerable`1 sources) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\MiniYaml.cs:line 262
   at OpenRA.MiniYaml.Load(IReadOnlyFileSystem fileSystem, IEnumerable`1 files, MiniYaml mapRules) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\MiniYaml.cs:line 394
   at OpenRA.Mods.Common.Widgets.Logic.ModContentLogic..ctor(Widget widget, Manifest mod, ModContent content, Action onCancel)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at OpenRA.ObjectCreator.CreateUsingArgs(ConstructorInfo ctor, Dictionary`2 args) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\ObjectCreator.cs:line 140
   at OpenRA.ObjectCreator.CreateObject[T](String className, Dictionary`2 args) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\ObjectCreator.cs:line 105
   at OpenRA.Widgets.Widget.<>c__DisplayClass3.<PostInit>b__2(String l) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:line 274
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OpenRA.Widgets.Widget.PostInit(WidgetArgs args) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:line 274
   at OpenRA.WidgetLoader.LoadWidget(WidgetArgs args, Widget parent, MiniYamlNode node) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Widgets\WidgetLoader.cs:line 75
   at OpenRA.WidgetLoader.LoadWidget(WidgetArgs args, Widget parent, String w) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Widgets\WidgetLoader.cs:line 44
   at OpenRA.Widgets.Ui.OpenWindow(String id, WidgetArgs args) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:line 62
   at OpenRA.Mods.Common.Widgets.Logic.ModContentPromptLogic.<>c__DisplayClassa.<.ctor>b__3()
   at OpenRA.Mods.Common.Widgets.ButtonWidget.<.ctor>b__e(MouseInput _)
   at OpenRA.Mods.Common.Widgets.ButtonWidget.HandleMouseInput(MouseInput mi)
   at OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:line 393
   at OpenRA.Widgets.Ui.HandleInput(MouseInput mi) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:line 102
   at OpenRA.DefaultInputHandler.<>c__DisplayClass7.<OnMouseInput>b__6() in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Input\InputHandler.cs:line 50
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Sync.cs:line 174
   at OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Input\InputHandler.cs:line 50
   at OpenRA.Platforms.Default.Sdl2Input.PumpInput(IInputHandler inputHandler) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Platforms.Default\Sdl2Input.cs:line 107
   at OpenRA.Platforms.Default.Sdl2GraphicsDevice.PumpInput(IInputHandler inputHandler) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Platforms.Default\Sdl2GraphicsDevice.cs:line 365
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Renderer.cs:line 155
   at OpenRA.Game.RenderTick() in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Game.cs:line 624
   at OpenRA.Game.Loop() in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Game.cs:line 734
   at OpenRA.Game.Run() in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Game.cs:line 752
   at OpenRA.Program.Run(String[] args) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 119
   at OpenRA.Program.Main(String[] args) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 40

If this is a duplicate, please inform me, i found errors that are similar, but not exactly the same.

Thanks in advance

### PR DESCRIPTION
**Pull request by LipkeGu**
This Pr fixes the crash when clicking the "Advanced Installation" Button in the Content installer and write a proper Installer Scheme.

closes  #296

ra2_test

### CODE REVIEW

**Comment by Phrohdoh** [comment]
`mono --debug OpenRA.Utility.exe ra2 --check-sequence-sprites` failed.

**Comment by LipkeGu** [comment]
thats because the language and ra2 mix isnt needed anymore but your build system needs it.

**Comment by LipkeGu** [comment]
```
1.19s$ mono --debug OpenRA.Utility.exe ra2 --check-yaml

Testing mod: Red Alert 2

OpenRA.Utility(1,1): Error: Failed with exception: System.AggregateException: One or more errors occurred. ---> OpenRA.YamlException: Actor type world: Trait name ResourceType: Required properties missing: Sequences, Type

  at OpenRA.ActorInfo..ctor (OpenRA.ObjectCreator creator, System.String name, OpenRA.MiniYaml node) [0x000df] in /home/travis/build/OpenRA/OpenRA.Game/GameRules/ActorInfo.cs:57 

  at OpenRA.Ruleset+<LoadDefaults>c__AnonStorey0.<>m__1 (OpenRA.MiniYamlNode k) [0x0001c] in /home/travis/build/OpenRA/OpenRA.Game/GameRules/Ruleset.cs:108 

  at OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey,TElement] (IEnumerable`1 source, System.Func`2 keySelector, System.Func`2 elementSelector, System.String debugName, System.Func`2 logKey, System.Func`2 logValue) [0x00073] in /home/travis/build/OpenRA/OpenRA.Game/Exts.cs:376 

  at OpenRA.Ruleset.MergeOrDefault[T] (System.String name, IReadOnlyFileSystem fileSystem, IEnumerable`1 files, OpenRA.MiniYaml additional, IReadOnlyDictionary`2 defaults, System.Func`2 makeObject) [0x0003e] in /home/travis/build/OpenRA/OpenRA.Game/GameRules/Ruleset.cs:94 

  at OpenRA.Ruleset+<LoadDefaults>c__AnonStorey0.<>m__0 () [0x00025] in /home/travis/build/OpenRA/OpenRA.Game/GameRules/Ruleset.cs:107 

  at System.Threading.Tasks.Task.InnerInvoke () <0x7fde6d89e790 + 0x0004f> in <filename unknown>:0 

  at System.Threading.Tasks.Task.Execute () <0x7fde6d89e050 + 0x00055> in <filename unknown>:0 

  --- End of inner exception stack trace ---

  at System.Threading.Tasks.Task.ThrowIfExceptional (Boolean includeTaskCanceledExceptions) <0x7fde6d89d920 + 0x00037> in <filename unknown>:0 

  at System.Threading.Tasks.Task.Wait (Int32 millisecondsTimeout, CancellationToken cancellationToken) <0x7fde6d89ed90 + 0x000c7> in <filename unknown>:0 

  at System.Threading.Tasks.Task.Wait (Int32 millisecondsTimeout) <0x7fde6d89ed60 + 0x00028> in <filename unknown>:0 

  at OpenRA.Ruleset.LoadDefaults (OpenRA.ModData modData) [0x00080] in /home/travis/build/OpenRA/OpenRA.Game/GameRules/Ruleset.cs:134 

  at OpenRA.ModData.<ModData>m__2 () [0x00001] in /home/travis/build/OpenRA/OpenRA.Game/ModData.cs:83 

  at System.Lazy`1[T].CreateValue () <0x7fde6d718d50 + 0x00174> in <filename unknown>:0 

---> (Inner Exception #0) OpenRA.YamlException: Actor type world: Trait name ResourceType: Required properties missing: Sequences, Type

  at OpenRA.ActorInfo..ctor (OpenRA.ObjectCreator creator, System.String name, OpenRA.MiniYaml node) [0x000df] in /home/travis/build/OpenRA/OpenRA.Game/GameRules/ActorInfo.cs:57 

  at OpenRA.Ruleset+<LoadDefaults>c__AnonStorey0.<>m__1 (OpenRA.MiniYamlNode k) [0x0001c] in /home/travis/build/OpenRA/OpenRA.Game/GameRules/Ruleset.cs:108 

  at OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey,TElement] (IEnumerable`1 source, System.Func`2 keySelector, System.Func`2 elementSelector, System.String debugName, System.Func`2 logKey, System.Func`2 logValue) [0x00073] in /home/travis/build/OpenRA/OpenRA.Game/Exts.cs:376 

  at OpenRA.Ruleset.MergeOrDefault[T] (System.String name, IReadOnlyFileSystem fileSystem, IEnumerable`1 files, OpenRA.MiniYaml additional, IReadOnlyDictionary`2 defaults, System.Func`2 makeObject) [0x0003e] in /home/travis/build/OpenRA/OpenRA.Game/GameRules/Ruleset.cs:94 

  at OpenRA.Ruleset+<LoadDefaults>c__AnonStorey0.<>m__0 () [0x00025] in /home/travis/build/OpenRA/OpenRA.Game/GameRules/Ruleset.cs:107 

  at System.Threading.Tasks.Task.InnerInvoke () <0x7fde6d89e790 + 0x0004f> in <filename unknown>:0 

  at System.Threading.Tasks.Task.Execute () <0x7fde6d89e050 + 0x00055> in <filename unknown>:0 <---
```

**Comment by abcdefg30** [comment]
Your last crash is another issue: #305

**Comment by LipkeGu** [comment]
ok i will wait untill your fix is in there

**Comment by LipkeGu** [comment]
Something is wrong it seems the checksums are wrong for the xwis ra2.mix file not found could also indicate damaged files ;( offline it works fine...

**Comment by GraionDilach** [comment]
XWIS probably uses the 1.006 mix.

**Comment by abcdefg30** [comment]
Partly(?) done in #355. (I'll have a closer look tomorrow.)

**Comment by abcdefg30** [comment]
Seems like there's nothing more to do here, as we can't resolve the "mixes inside mixes" issue without breaking travis.

**Pull request closed without merging**
