### PR TITLE
Balance Update 1.0

### PR DESCRIPTION
**Pull request by vietman391**
Changes:

- Chrono Miner: Decreased speed & capacity, increased HP
- Ore Miner: Ditto, except speed
- Rocketeer: Decreased HP
- Harrier: Decreased HP & Damage (They no longer 1-hit everything)
- Oil Derrick: Decreased capture bonus from 1000 to 500
- Attack Dog: Decreased HP & (possibly) rate of fire (I tested it, nothing really changed)

### CODE REVIEW

**Comment by GraionDilach** [comment]
You see, we are aiming to restore the original values first - which aren't done even. RA2 was the most balanced Westwood C&C actually. Most of your changes are nonsense tbh.

I understand you aim to get what's done playable, but changing these such early is drastic and really makes no sense. I'll have to :-1: this.

BTW, yes, `AttackLeap` also ignores `ReloadDelay`.

**Comment by vietman391** [comment]
It makes more sense when you actually play the mod using these changes, but I understand how small changes like these can make you uncomfortable.

I'm not doing this to give an impression that I'm right about these changes, it's just that I want to see how I can _temporarily_ balance ra2 so that I can get another good stream going while playing ra2 for fun :)

**Comment by GraionDilach** [comment]
The main issue is that this isn't even streamable technically.

Also, you should have realized it by now - since I'll assume you're Spy\` -, that if you end up successfully sneaking in some "temporary" workarounds, after a short while people will forget to revert them and considering how lousy the RA2 mod always was, I'm really not welcoming balance workarounds.

**Comment by vietman391** [comment]
I wasn't the one who started a pull request in the first place; it just so happens Mailaender moved my fork to work for here.

I don't intend for any of my balance changes to pass; I'm just doing this for myself and anyone who's interested.

I understand that you have a personal opinion towards me; but I don't think there is a need for that, and it's not very productive.

**Comment by Mailaender** [comment]
This still seems to base off on an older version of the RA2 mod, so we can't see the real changes nor integrate it. See https://help.github.com/articles/using-git-rebase/ on how to resolve this.

We are indeed only interested in fixes that restore vanilla balancing for now. I assume the harrier one-shot kill every building is a bug for example as the weapon rules don't translate 1:1 into OpenRA.

**Comment by Phrohdoh** [comment]
> We are indeed only interested in fixes that restore vanilla balancing for now.

So is the power-down going to be removed then?

**Comment by GraionDilach** [comment]
Actually the powerdown feature is still less arbitrary than the changes in this PR (for example the miner changes, which are actually an issue of gem worth, which has 250 than the supposed 100 per bail...)

**Comment by Phrohdoh** [comment]
I agree that this shouldn't be taken at this time.
Balance (whatever one may think of it) should definitely match vanilla (as close as sanely possible) before making tweaks.

**Comment by Mailaender** [comment]
We should focus on fixing the rules as in https://github.com/OpenRA/ra2/pull/179 instead changing them. At least for now.

**Pull request closed without merging**
