### PR TITLE
Improved Kirov auto targeting

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/ra2/issues/705.

### CODE REVIEW

**Comment by sorcerer86pt** [comment]
well test this one

**Comment by sorcerer86pt** [comment]
it's asking for a older engine:

```
 Fabio@FABIO-ROG  G:\ra2   pr/706 ≣  ./make all
OpenRA engine version playtest-20200118 is required.
Deleting engine version release-20200202.
Downloading engine...
Version strings set to 'playtest-20200118'.
Fetching NuGet.
```

**Comment by sorcerer86pt** [comment]
Well it kinda works... it still has a problem when 2+ kirovs wants to attack the same target. Also sometimes they forget/ don't see a unit even when it's close to another one.

Also some clipping issues when 2 kirovs are near each other. See the attached video.

[Kirov auto targeting](https://drive.google.com/file/d/1JOVGGIfwcnK9a4Ayz-S4gdOUtc1Rrfcy/view?usp=sharing)

**Comment by Mailaender** [comment]
Yes, it is still far from optimal. This only fixes the kirov not shooting if it is not facing in the upfront direction. There is still a lot to do. Especially the moving forward while bombarding feature is missing.

**Comment by sorcerer86pt** [comment]
I see.

Try to also use the master branch engine version.

**Comment by Mailaender** [comment]
I am. Just you weren't.

**Comment by sorcerer86pt** [comment]
i just have made the make clean, and used the pull request  branch

**Comment by Mailaender** [comment]
It happened due to https://github.com/OpenRA/ra2/commit/6caa0a0602866e21e6e70f3c64ef5ad5735b0c3f which was sneaked in without a pull request.

**Pull request merged**
